import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';

import { BankComponent } from './bank/bank.component';
import { ItemComponent} from './item.component';
import { ItemService} from './item.service';


@NgModule({
  declarations: [
    AppComponent,
    BankComponent,
    ItemComponent
   
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [ItemService],
  bootstrap: [AppComponent]
})
export class AppModule { }
